### ISSUE TITLE
Add a hook to notify clients that the CA is about to expire

### ISSUE THREAD

**Issue by skourta** [canonical/self-signed-certificates-operator#229]
### Enhancement Proposal

Currently, the operator does not notify the clients that the CA is about to expire.
A hook to notify the clients that a CA is about to expire should be added to trigger the rotation on the client side and request new CSRs.

**Comment by saltiyazan** [comment]
Thanks for openning the issue.

The CA rotation is planned to be implemented soon in `self-signed-certificates-operator` following [this](https://docs.google.com/document/d/1fbyUzSX_VUtSNgN2qWbiWe_L-jqNT8GVrQ83mEB8sjI/edit) spec.

We don't plan adding a hook for notifying requirers of CA changes, the requirer should be able to see the CA in the certificate it receives or use the the `certificate-transfer` interface if it does not requirer signed certificates and only needs to know about the CA certs to trust them.

**Comment by gruyaume** [comment]
Closing this enhancement proposal as we won't complete it. As @saltiyazan mentioned, the focus will be on having proper CA certificate renewal and the TLS requirer will be noticed through the certificate available event.
