### ISSUE TITLE
Add juju action for ad-hoc certificates

### ISSUE THREAD

**Issue by sed-i** [canonical/self-signed-certificates-operator#32]
For debugging/experimentation it would be helpful if the charm had an [action](https://juju.is/docs/sdk/actions#heading--complex-action-example) that would take the same args as [`generate_csr` ](https://github.com/canonical/tls-certificates-interface/blob/d08dc35426ae6a790a3f6fc11088f29840ceb217/lib/charms/tls_certificates_interface/v2/tls_certificates.py#L799) (except private key) and output the (newly generated) private key and signed cert.

**Comment by gruyaume** [comment]
We do have the [tls-certificates-requirer](https://charmhub.io/tls-certificates-requirer) that can leverage the `tls-certificates` interface and be used for receiving certs from self-signed-certificates operator. Does this satisfy the need?

**Comment by gruyaume** [comment]
@sed-i Any comment before I close this issue?

**Comment by sed-i** [comment]
The tls-certificates-requirer addresses the exact use case I was looking for, but I think usability is higher with an action, because it is easier to extract content from `juju run ... --format json | jq ...` .
The analogous with `juju show-unit` would require us to know the app name.
