### ISSUE TITLE
Add action to fetch issues certs

### ISSUE THREAD

**Issue by sed-i** [canonical/self-signed-certificates-operator#9]
For integration test it would be handy if the charm had a action to ouput the certs issues.
Currently the workaround is to poke in 
```bash
juju show-unit traefik/0 --format=json \
  | jq -r '."traefik/0"."relation-info"[3]."application-data".certificates' \
  | jq -r ".[0].certificate"
```

**Comment by saltiyazan** [comment]
PR #17 addresses this issue and it's ready to be merged. Let me know if I can merge it and close this issue @sed-i

**Comment by saltiyazan** [comment]
PR #17 added an action that fetches all certs and lists them per application by csr.
PR is merged, therefore, closing this issue.
